In [2]:
# Membuat list
data = [10, 20, 'Python', True, 3.14]

# Akses & slicing
print(data[0]) # → 10
print(data[-1]) # → 3.14 (dari belakang)
print(data[1:3]) # → [20, 'Python']

# Manipulasi
data.append(99) # tambah di akhir
data.insert(1, 55) # sisipkan di posisi 1
data.remove(20) # hapus nilai pertama = 20

10
3.14
[20, 'Python']


In [4]:
mahasiswa = {
 'nama': 'Budi Santoso',
 'nim': '2024001',
 'prodi': 'Informatika',
 'ipk': 3.85
}
# Akses nilai
print(mahasiswa['nama']) # → 'Budi Santoso'
print(mahasiswa.get('usia', 0)) # default jika key tak ada

# Update dan hapus
mahasiswa['angkatan'] = 2024 # tambah key baru
del mahasiswa['nim'] # hapus key


Budi Santoso
0


In [5]:
import numpy as np
# Dari list Python
a1D = np.array([1, 2, 3, 4, 5]) # 1D
a2D = np.array([[1,2,3],[4,5,6]]) # 2D

# Array dengan nilai inisial
zeros = np.zeros((3, 4)) # nol semua
ones = np.ones((2, 3)) # satu semua
eye = np.eye(4) # matriks identitas
full = np.full((2, 2), 7) # nilai konstan

# Sequence
arange = np.arange(0, 20, 2) # 0,2,4,...18
linsp = np.linspace(0, 1, 11) # 11 titik merata

# Array acak (reproducible)
rng = np.random.default_rng(seed=42)
rand_int = rng.integers(0, 100, (3, 4))
rand_flt = rng.normal(loc=0, scale=1, size=(100,))

In [6]:
# Operasi aritmetika vektorisasi
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
print(a + b) # → [11 22 33 44 55]
print(a * b) # → [10 40 90 160 250]
print(a ** 2) # → [1 4 9 16 25]

# Universal functions (ufuncs)
np.sqrt(a) # akar kuadrat tiap elemen
np.exp(a) # eksponensial (e^x)
np.log(b) # logaritma natural

# Fungsi statistik
data = rng.normal(0, 1, 1000)
print(f'Mean: {np.mean(data):.4f}')
print(f'Std: {np.std(data):.4f}')
print(f'Min: {np.min(data):.4f}')
print(f'Max: {np.max(data):.4f}')
print(f'Q1: {np.percentile(data,25):.4f}')
print(f'Q3: {np.percentile(data,75):.4f}')


[11 22 33 44 55]
[ 10  40  90 160 250]
[ 1  4  9 16 25]
Mean: -0.0163
Std: 1.0008
Min: -3.6484
Max: 3.1789
Q1: -0.6897
Q3: 0.6163


In [7]:
import pandas as pd
# Series dari list — index default 0,1,2...
s1 = pd.Series([85, 92, 78, 95, 88])

# Series dengan index kustom
nilai = pd.Series(
 [85, 92, 78, 95],
 index=['Alice','Bob','Caca','Dina']
)
print(nilai['Bob']) # → 92
print(nilai[nilai>80]) # filter
print(nilai.mean()) # → 87.5
print(nilai.describe()) # statistik lengkap

92
Alice    85
Bob      92
Dina     95
dtype: int64
87.5
count     4.000000
mean     87.500000
std       7.593857
min      78.000000
25%      83.250000
50%      88.500000
75%      92.750000
max      95.000000
dtype: float64


In [8]:
# Membuat DataFrame dari dictionary
data = {
 'nama': ['Ali','Budi','Caca','Dina'],
 'usia': [22, 25, 21, 23],
 'kota': ['Jakarta','Bandung','Surabaya','Medan'],
 'ipk': [3.8, 3.5, 3.9, 3.7]
}
df = pd.DataFrame(data)

# Informasi dasar
print(df.shape) # → (4, 4)
print(df.dtypes) # tipe data per kolom
print(df.columns) # nama-nama kolom


(4, 4)
nama     object
usia      int64
kota     object
ipk     float64
dtype: object
Index(['nama', 'usia', 'kota', 'ipk'], dtype='object')


In [28]:
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"
df = pd.read_csv(url)
# Filter satu kondisi
penumpang_selamat = df[df['Survived'] == 1]
penumpang_wanita = df[df['Sex'] == 'female']

# Filter kondisi ganda (& = AND, | = OR)
wanita_kelas1 = df[(df['Sex']=='female') &
 (df['Pclass']==1)]

# Seleksi kolom tertentu
print(df)
print(df.columns)

     PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ... 

In [15]:
# Pola dasar: groupby → aggregation
df.groupby('Pclass')['Survived'].mean()

# Agregasi multiple kolom & fungsi
hasil = df.groupby('Pclass').agg(
 total = ('PassengerId', 'count'),
 selamat = ('Survived', 'sum'),
 pct_selamat= ('Survived', 'mean'),
 rata_usia = ('Age', 'mean'),
 max_fare = ('Fare', 'max')
)
hasil = hasil.round(3)
print(hasil)

# GroupBy multi-kolom
df.groupby(['Pclass','Sex'])['Survived']\
 .mean().unstack().round(3)


        total  selamat  pct_selamat  rata_usia  max_fare
Pclass                                                  
1         216      136        0.630     38.233   512.329
2         184       87        0.473     29.878    73.500
3         491      119        0.242     25.141    69.550


Sex,female,male
Pclass,,
1,0.968,0.369
2,0.921,0.157
3,0.500,0.135


In [16]:
missing = df.isnull().sum()
print(missing)

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64


In [17]:
missing_percent = (df.isnull().sum()/len(df))*100
print(missing_percent)

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64


In [19]:
missing_info = pd.DataFrame({
    'Missing Values' : df.isnull().sum(),
    'Percentage' : (df.isnull().sum()/len(df)) * 100
})

missing_info = missing_info[missing_info['Missing Values'] > 0]

print(missing_info)

          Missing Values  Percentage
Age                  177   19.865320
Cabin                687   77.104377
Embarked               2    0.224467


In [43]:
count = df['Survived'].value_counts()
percent = df['Survived'].value_counts(normalize=True) * 100

result = pd.DataFrame({
    'Jumlah' : count,
    'Presentase' : percent
}).reset_index()

result.columns = ['Status','Jumlah','Presentase']

result['Status'] = result['Status'].map({0: "Tidak Selamat", 1: "Selamat"})
print(result)

          Status  Jumlah  Presentase
0  Tidak Selamat     549   61.616162
1        Selamat     342   38.383838


In [49]:
# Filter kondisi ganda (& = AND, | = OR)
wanita_kelas1 = (df[(df['Sex']=='female') & (df['Pclass']==1)])
total = len(wanita_kelas1)
mean_age = wanita_kelas1['Age'].mean()

print(f'Passenger Wanita 1st Class : {total}')
print(f'Rata-rata Usia : {mean_age:.2f}')

Passenger Wanita 1st Class : 94
Rata-rata Usia : 34.61


In [55]:
survived_byclass = df.groupby('Pclass')['Survived'].mean().sort_values(ascending=False)

print(survived_byclass)

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64


In [58]:
sexClass_surv = df.groupby(['Sex', 'Pclass'])['Survived'].mean().reset_index()

#print(sexClass_surv)

pivot = df.pivot_table(values='Survived',
                       index='Sex',
                       columns='Pclass',
                       aggfunc='mean')

print(pivot)

Pclass         1         2         3
Sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447


In [ ]:
#Q1 - Jumlah Kolom dan baris
#=======================================

#Jumlah baris = 891 
#Jumlah kolom = 12 'PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp,'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'

#Note: Setelah melakukan akses file csv dengan url di cell 28, output yang dikeluarkan saat menggunakan
#print(df) dan print(df.columns), akan keluar total rows dan column juga nama column yang tersedia.

In [ ]:
#Q2 - Missing Values
#==========================

# 1. Age - 177 - 19.86%
# 2. Cabin - 687 - 77.10%
# 3. Embarked - 2 - 0.22%

#Note: Pada cell 19, variable missing_info dibuat untuk langsung mencari total missing values dan precentage di setiap kolom
#lalu saya menuliskan codes untuk hanya menampilkan list yang memiliki data blank 

In [ ]:
#Q3 - Penumpang Selamat
#==========================

#Selamat = 342 orang - 38.38%

#Note: Setelah melakukan pengecekan di cell 43, ditemukan sebanyak 342 orang atau 38.38% berstatus Selamat

In [ ]:
#Q4 - Filter Wanita Kelas 1 (Total dan Rata-rata Usia)
#==========================

#Total Penumpang Wanita Kelas 1 : 94
#Rata-rata Usia : 34.61

#Note: Codes di cell 49

In [ ]:
#Q5 - Groupby Survived by Class
#==========================

#Mean Survived Tertinggi : Class 1 = 0.62

#Note: Codes di cell 55

In [ ]:
#Q6 - Analisis Tambahan
#==========================

#Berdasarkan hasil codes di cell 58, terlihat survival rate antara passenger laki-laki dengan perempuan memiliki
#perbedaan yang significant antar kelas, bahkan passenger laki-laki di kelas 1 memiliki survival rate yang lebih 
#rendah daripada passenger perempuan di kelas 3 